export const colors = {
  //default containers
  defaultContainerColor: '#fafafa',
  //default sections
  defaultSectionHeaderColor: '#fafafa',
  defaultSectionBackgroundColor: '#fafafa',
  defaultSectionTextColor: '#000',
  //default headers
  defaultHeaderBorder: '#607d8b',
  defaultHeaderBackground: '#607d8b',
  defaultHeaderTextColor: '#fafafa',
  //default footers
  defaultFooterBorder: '#607d8b',
  defaultFooterBackground: '#607d8b',
  defaultFooterTextColor: '#fafafa',
  //default cards
  defaultCardHeaderColor: '#607d8b',
  defaultCardHeaderTextColor: '#fafafa',
  defaultCardBorder: '#607d8b',
  defaultCardBackground: '#fafafa',
  defaultCardTextColor: '#000',
  defaultCardHoverColor: '#34515e',
  defaultCardHoverTextColor: '#fafafa',
  //default inputs
  defaultInputBorder: '#607d8b',
  defaultInputBackground: '#fafafa',
  defaultInputTextColor: '#000',
  defaultInputLabel: '#607d8b',
  //default buttons
  defaultButtonBorder: '#607d8b',
  defaultButtonBackground: '#607d8b',
  defaultButtonTextColor: '#000',
  defaultButtonHoverColor: '#34515e',
  defaultButtonHoverTextColor: '#fafafa',
  //special colors
  errorColor: '#e91e63',
  successColor: '#00e676',
  warningColor: '#ffb300',
};
export const sizes = {};