export const colors = {
  //default containers
  defaultContainerColor: "#fafafa",
  //default sections
  defaultSectionHeaderColor: "#fafafa",
  defaultSectionBackgroundColor: "#fafafa",
  defaultSectionTextColor: "#000",
  //default headers
  defaultHeaderBorder: "#3A8687",
  defaultHeaderBackground: "#3A8687",
  defaultHeaderTextColor: "#fafafa",
  //default footers
  defaultFooterBorder: "#3A8687",
  defaultFooterBackground: "#3A8687",
  defaultFooterTextColor: "#fafafa",
  //default cards
  defaultCardHeaderColor: "#3A8687",
  defaultCardHeaderTextColor: "#fafafa",
  defaultCardBorder: "#3A8687",
  defaultCardBackground: "#fafafa",
  defaultCardTextColor: "#000",
  defaultCardHoverColor: "#173E56",
  defaultCardHoverTextColor: "#fafafa",
  //default inputs
  defaultInputBorder: "#3A8687",
  defaultInputBackground: "#fafafa",
  defaultInputTextColor: "#000",
  defaultInputLabel: "#3A8687",
  //default buttons
  defaultButtonBorder: "#3A8687",
  defaultButtonBackground: "#3A8687",
  defaultButtonTextColor: "#000",
  defaultButtonHoverColor: "#173E56",
  defaultButtonHoverTextColor: "#fafafa",
  //special colors
  errorColor: "#E54A26",
  successColor: "#00e676",
  warningColor: "#DFF688"
};
export const sizes = {};
